/*
 * This file has been generated by the onto2vocabularyclass tool
 * copyright (C) 2007-2010 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#include "nrl.h"
#include <QThreadStorage>

class NrlPrivate
{
public:
    NrlPrivate()
        : nrl_namespace( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#", QUrl::StrictMode ) ),
          nrl_AsymmetricProperty( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#AsymmetricProperty", QUrl::StrictMode ) ),
          nrl_Configuration( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#Configuration", QUrl::StrictMode ) ),
          nrl_Data( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#Data", QUrl::StrictMode ) ),
          nrl_DefaultGraph( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#DefaultGraph", QUrl::StrictMode ) ),
          nrl_DefiningProperty( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#DefiningProperty", QUrl::StrictMode ) ),
          nrl_DiscardableInstanceBase( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#DiscardableInstanceBase", QUrl::StrictMode ) ),
          nrl_DocumentGraph( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#DocumentGraph", QUrl::StrictMode ) ),
          nrl_ExternalViewSpecification( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#ExternalViewSpecification", QUrl::StrictMode ) ),
          nrl_FunctionalProperty( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#FunctionalProperty", QUrl::StrictMode ) ),
          nrl_Graph( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#Graph", QUrl::StrictMode ) ),
          nrl_GraphMetadata( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#GraphMetadata", QUrl::StrictMode ) ),
          nrl_GraphView( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#GraphView", QUrl::StrictMode ) ),
          nrl_InstanceBase( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#InstanceBase", QUrl::StrictMode ) ),
          nrl_InverseFunctionalProperty( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#InverseFunctionalProperty", QUrl::StrictMode ) ),
          nrl_KnowledgeBase( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#KnowledgeBase", QUrl::StrictMode ) ),
          nrl_NonDefiningProperty( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#NonDefiningProperty", QUrl::StrictMode ) ),
          nrl_Ontology( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#Ontology", QUrl::StrictMode ) ),
          nrl_ReflexiveProperty( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#ReflexiveProperty", QUrl::StrictMode ) ),
          nrl_RuleViewSpecification( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#RuleViewSpecification", QUrl::StrictMode ) ),
          nrl_Schema( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#Schema", QUrl::StrictMode ) ),
          nrl_Semantics( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#Semantics", QUrl::StrictMode ) ),
          nrl_SymmetricProperty( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#SymmetricProperty", QUrl::StrictMode ) ),
          nrl_TransitiveProperty( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#TransitiveProperty", QUrl::StrictMode ) ),
          nrl_ViewSpecification( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#ViewSpecification", QUrl::StrictMode ) ),
          nrl_cardinality( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#cardinality", QUrl::StrictMode ) ),
          nrl_coreGraphMetadataFor( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#coreGraphMetadataFor", QUrl::StrictMode ) ),
          nrl_equivalentGraph( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#equivalentGraph", QUrl::StrictMode ) ),
          nrl_externalRealizer( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#externalRealizer", QUrl::StrictMode ) ),
          nrl_graphMetadataFor( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#graphMetadataFor", QUrl::StrictMode ) ),
          nrl_hasSemantics( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#hasSemantics", QUrl::StrictMode ) ),
          nrl_hasSpecification( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#hasSpecification", QUrl::StrictMode ) ),
          nrl_imports( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#imports", QUrl::StrictMode ) ),
          nrl_inverseProperty( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#inverseProperty", QUrl::StrictMode ) ),
          nrl_maxCardinality( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality", QUrl::StrictMode ) ),
          nrl_minCardinality( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#minCardinality", QUrl::StrictMode ) ),
          nrl_realizes( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#realizes", QUrl::StrictMode ) ),
          nrl_rule( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#rule", QUrl::StrictMode ) ),
          nrl_ruleLanguage( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#ruleLanguage", QUrl::StrictMode ) ),
          nrl_semanticsDefinedBy( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#semanticsDefinedBy", QUrl::StrictMode ) ),
          nrl_subGraphOf( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#subGraphOf", QUrl::StrictMode ) ),
          nrl_superGraphOf( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#superGraphOf", QUrl::StrictMode ) ),
          nrl_updatable( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#updatable", QUrl::StrictMode ) ),
          nrl_viewOn( QUrl::fromEncoded( "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#viewOn", QUrl::StrictMode ) ) {
    }

    QUrl nrl_namespace;
    QUrl nrl_AsymmetricProperty;
    QUrl nrl_Configuration;
    QUrl nrl_Data;
    QUrl nrl_DefaultGraph;
    QUrl nrl_DefiningProperty;
    QUrl nrl_DiscardableInstanceBase;
    QUrl nrl_DocumentGraph;
    QUrl nrl_ExternalViewSpecification;
    QUrl nrl_FunctionalProperty;
    QUrl nrl_Graph;
    QUrl nrl_GraphMetadata;
    QUrl nrl_GraphView;
    QUrl nrl_InstanceBase;
    QUrl nrl_InverseFunctionalProperty;
    QUrl nrl_KnowledgeBase;
    QUrl nrl_NonDefiningProperty;
    QUrl nrl_Ontology;
    QUrl nrl_ReflexiveProperty;
    QUrl nrl_RuleViewSpecification;
    QUrl nrl_Schema;
    QUrl nrl_Semantics;
    QUrl nrl_SymmetricProperty;
    QUrl nrl_TransitiveProperty;
    QUrl nrl_ViewSpecification;
    QUrl nrl_cardinality;
    QUrl nrl_coreGraphMetadataFor;
    QUrl nrl_equivalentGraph;
    QUrl nrl_externalRealizer;
    QUrl nrl_graphMetadataFor;
    QUrl nrl_hasSemantics;
    QUrl nrl_hasSpecification;
    QUrl nrl_imports;
    QUrl nrl_inverseProperty;
    QUrl nrl_maxCardinality;
    QUrl nrl_minCardinality;
    QUrl nrl_realizes;
    QUrl nrl_rule;
    QUrl nrl_ruleLanguage;
    QUrl nrl_semanticsDefinedBy;
    QUrl nrl_subGraphOf;
    QUrl nrl_superGraphOf;
    QUrl nrl_updatable;
    QUrl nrl_viewOn;
};

QThreadStorage<NrlPrivate*> qts_nrl;
NrlPrivate* s_nrl() {
    if( !qts_nrl.hasLocalData() )
        qts_nrl.setLocalData( new NrlPrivate );
    return qts_nrl.localData();
}

QUrl Soprano::Vocabulary::NRL::nrlNamespace()
{
    return s_nrl()->nrl_namespace;
}

QUrl Soprano::Vocabulary::NRL::AsymmetricProperty()
{
    return s_nrl()->nrl_AsymmetricProperty;
}

QUrl Soprano::Vocabulary::NRL::Configuration()
{
    return s_nrl()->nrl_Configuration;
}

QUrl Soprano::Vocabulary::NRL::Data()
{
    return s_nrl()->nrl_Data;
}

QUrl Soprano::Vocabulary::NRL::DefaultGraph()
{
    return s_nrl()->nrl_DefaultGraph;
}

QUrl Soprano::Vocabulary::NRL::DefiningProperty()
{
    return s_nrl()->nrl_DefiningProperty;
}

QUrl Soprano::Vocabulary::NRL::DiscardableInstanceBase()
{
    return s_nrl()->nrl_DiscardableInstanceBase;
}

QUrl Soprano::Vocabulary::NRL::DocumentGraph()
{
    return s_nrl()->nrl_DocumentGraph;
}

QUrl Soprano::Vocabulary::NRL::ExternalViewSpecification()
{
    return s_nrl()->nrl_ExternalViewSpecification;
}

QUrl Soprano::Vocabulary::NRL::FunctionalProperty()
{
    return s_nrl()->nrl_FunctionalProperty;
}

QUrl Soprano::Vocabulary::NRL::Graph()
{
    return s_nrl()->nrl_Graph;
}

QUrl Soprano::Vocabulary::NRL::GraphMetadata()
{
    return s_nrl()->nrl_GraphMetadata;
}

QUrl Soprano::Vocabulary::NRL::GraphView()
{
    return s_nrl()->nrl_GraphView;
}

QUrl Soprano::Vocabulary::NRL::InstanceBase()
{
    return s_nrl()->nrl_InstanceBase;
}

QUrl Soprano::Vocabulary::NRL::InverseFunctionalProperty()
{
    return s_nrl()->nrl_InverseFunctionalProperty;
}

QUrl Soprano::Vocabulary::NRL::KnowledgeBase()
{
    return s_nrl()->nrl_KnowledgeBase;
}

QUrl Soprano::Vocabulary::NRL::NonDefiningProperty()
{
    return s_nrl()->nrl_NonDefiningProperty;
}

QUrl Soprano::Vocabulary::NRL::Ontology()
{
    return s_nrl()->nrl_Ontology;
}

QUrl Soprano::Vocabulary::NRL::ReflexiveProperty()
{
    return s_nrl()->nrl_ReflexiveProperty;
}

QUrl Soprano::Vocabulary::NRL::RuleViewSpecification()
{
    return s_nrl()->nrl_RuleViewSpecification;
}

QUrl Soprano::Vocabulary::NRL::Schema()
{
    return s_nrl()->nrl_Schema;
}

QUrl Soprano::Vocabulary::NRL::Semantics()
{
    return s_nrl()->nrl_Semantics;
}

QUrl Soprano::Vocabulary::NRL::SymmetricProperty()
{
    return s_nrl()->nrl_SymmetricProperty;
}

QUrl Soprano::Vocabulary::NRL::TransitiveProperty()
{
    return s_nrl()->nrl_TransitiveProperty;
}

QUrl Soprano::Vocabulary::NRL::ViewSpecification()
{
    return s_nrl()->nrl_ViewSpecification;
}

QUrl Soprano::Vocabulary::NRL::cardinality()
{
    return s_nrl()->nrl_cardinality;
}

QUrl Soprano::Vocabulary::NRL::coreGraphMetadataFor()
{
    return s_nrl()->nrl_coreGraphMetadataFor;
}

QUrl Soprano::Vocabulary::NRL::equivalentGraph()
{
    return s_nrl()->nrl_equivalentGraph;
}

QUrl Soprano::Vocabulary::NRL::externalRealizer()
{
    return s_nrl()->nrl_externalRealizer;
}

QUrl Soprano::Vocabulary::NRL::graphMetadataFor()
{
    return s_nrl()->nrl_graphMetadataFor;
}

QUrl Soprano::Vocabulary::NRL::hasSemantics()
{
    return s_nrl()->nrl_hasSemantics;
}

QUrl Soprano::Vocabulary::NRL::hasSpecification()
{
    return s_nrl()->nrl_hasSpecification;
}

QUrl Soprano::Vocabulary::NRL::imports()
{
    return s_nrl()->nrl_imports;
}

QUrl Soprano::Vocabulary::NRL::inverseProperty()
{
    return s_nrl()->nrl_inverseProperty;
}

QUrl Soprano::Vocabulary::NRL::maxCardinality()
{
    return s_nrl()->nrl_maxCardinality;
}

QUrl Soprano::Vocabulary::NRL::minCardinality()
{
    return s_nrl()->nrl_minCardinality;
}

QUrl Soprano::Vocabulary::NRL::realizes()
{
    return s_nrl()->nrl_realizes;
}

QUrl Soprano::Vocabulary::NRL::rule()
{
    return s_nrl()->nrl_rule;
}

QUrl Soprano::Vocabulary::NRL::ruleLanguage()
{
    return s_nrl()->nrl_ruleLanguage;
}

QUrl Soprano::Vocabulary::NRL::semanticsDefinedBy()
{
    return s_nrl()->nrl_semanticsDefinedBy;
}

QUrl Soprano::Vocabulary::NRL::subGraphOf()
{
    return s_nrl()->nrl_subGraphOf;
}

QUrl Soprano::Vocabulary::NRL::superGraphOf()
{
    return s_nrl()->nrl_superGraphOf;
}

QUrl Soprano::Vocabulary::NRL::updatable()
{
    return s_nrl()->nrl_updatable;
}

QUrl Soprano::Vocabulary::NRL::viewOn()
{
    return s_nrl()->nrl_viewOn;
}
