/*
 * This file has been generated by the onto2vocabularyclass tool
 * copyright (C) 2007-2008 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#include "xesam.h"
#include <QThreadStorage>

class XesamPrivate
{
public:
    XesamPrivate()
        : xesam_namespace( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#", QUrl::StrictMode ) ),
          xesam_35mmEquivalent( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#35mmEquivalent", QUrl::StrictMode ) ),
          xesam_Annotation( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Annotation", QUrl::StrictMode ) ),
          xesam_Archive( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Archive", QUrl::StrictMode ) ),
          xesam_ArchivedFile( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#ArchivedFile", QUrl::StrictMode ) ),
          xesam_Audio( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Audio", QUrl::StrictMode ) ),
          xesam_AudioList( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#AudioList", QUrl::StrictMode ) ),
          xesam_BlockDevice( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#BlockDevice", QUrl::StrictMode ) ),
          xesam_Bookmark( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Bookmark", QUrl::StrictMode ) ),
          xesam_CommunicationChannel( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#CommunicationChannel", QUrl::StrictMode ) ),
          xesam_Contact( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Contact", QUrl::StrictMode ) ),
          xesam_ContactGroup( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#ContactGroup", QUrl::StrictMode ) ),
          xesam_Content( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Content", QUrl::StrictMode ) ),
          xesam_DataObject( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#DataObject", QUrl::StrictMode ) ),
          xesam_DeletedFile( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#DeletedFile", QUrl::StrictMode ) ),
          xesam_Document( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Document", QUrl::StrictMode ) ),
          xesam_Documentation( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Documentation", QUrl::StrictMode ) ),
          xesam_Email( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Email", QUrl::StrictMode ) ),
          xesam_EmailAttachment( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#EmailAttachment", QUrl::StrictMode ) ),
          xesam_EmbeddedObject( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#EmbeddedObject", QUrl::StrictMode ) ),
          xesam_File( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#File", QUrl::StrictMode ) ),
          xesam_FileSystem( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#FileSystem", QUrl::StrictMode ) ),
          xesam_Filelike( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Filelike", QUrl::StrictMode ) ),
          xesam_Folder( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Folder", QUrl::StrictMode ) ),
          xesam_IMAP4Message( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#IMAP4Message", QUrl::StrictMode ) ),
          xesam_IMMessage( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#IMMessage", QUrl::StrictMode ) ),
          xesam_Image( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Image", QUrl::StrictMode ) ),
          xesam_MailingList( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#MailingList", QUrl::StrictMode ) ),
          xesam_MailingListEmail( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#MailingListEmail", QUrl::StrictMode ) ),
          xesam_Media( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Media", QUrl::StrictMode ) ),
          xesam_MediaList( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#MediaList", QUrl::StrictMode ) ),
          xesam_Message( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Message", QUrl::StrictMode ) ),
          xesam_MessageboxMessage( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#MessageboxMessage", QUrl::StrictMode ) ),
          xesam_Music( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Music", QUrl::StrictMode ) ),
          xesam_NewsGroup( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#NewsGroup", QUrl::StrictMode ) ),
          xesam_NewsGroupEmail( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#NewsGroupEmail", QUrl::StrictMode ) ),
          xesam_OfflineMedia( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#OfflineMedia", QUrl::StrictMode ) ),
          xesam_Organization( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Organization", QUrl::StrictMode ) ),
          xesam_POP3Message( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#POP3Message", QUrl::StrictMode ) ),
          xesam_Person( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Person", QUrl::StrictMode ) ),
          xesam_PersonalEmail( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#PersonalEmail", QUrl::StrictMode ) ),
          xesam_Photo( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Photo", QUrl::StrictMode ) ),
          xesam_Presentation( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Presentation", QUrl::StrictMode ) ),
          xesam_Project( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Project", QUrl::StrictMode ) ),
          xesam_RSSFeed( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#RSSFeed", QUrl::StrictMode ) ),
          xesam_RSSMessage( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#RSSMessage", QUrl::StrictMode ) ),
          xesam_RemoteFile( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#RemoteFile", QUrl::StrictMode ) ),
          xesam_RemoteMessageboxMessage( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#RemoteMessageboxMessage", QUrl::StrictMode ) ),
          xesam_RemoteResource( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#RemoteResource", QUrl::StrictMode ) ),
          xesam_RevisionControlledFile( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#RevisionControlledFile", QUrl::StrictMode ) ),
          xesam_RevisionControlledRepository( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#RevisionControlledRepository", QUrl::StrictMode ) ),
          xesam_SoftwarePackage( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#SoftwarePackage", QUrl::StrictMode ) ),
          xesam_Source( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Source", QUrl::StrictMode ) ),
          xesam_SourceCode( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#SourceCode", QUrl::StrictMode ) ),
          xesam_Spreadsheet( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Spreadsheet", QUrl::StrictMode ) ),
          xesam_SystemResource( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#SystemResource", QUrl::StrictMode ) ),
          xesam_Tag( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Tag", QUrl::StrictMode ) ),
          xesam_Text( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Text", QUrl::StrictMode ) ),
          xesam_TextDocument( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#TextDocument", QUrl::StrictMode ) ),
          xesam_UncategorizedText( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#UncategorizedText", QUrl::StrictMode ) ),
          xesam_Video( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Video", QUrl::StrictMode ) ),
          xesam_Visual( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#Visual", QUrl::StrictMode ) ),
          xesam_XML( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#XML", QUrl::StrictMode ) ),
          xesam_acl( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#acl", QUrl::StrictMode ) ),
          xesam_album( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#album", QUrl::StrictMode ) ),
          xesam_albumArtist( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#albumArtist", QUrl::StrictMode ) ),
          xesam_albumGain( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#albumGain", QUrl::StrictMode ) ),
          xesam_albumPeakGain( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#albumPeakGain", QUrl::StrictMode ) ),
          xesam_albumTrackCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#albumTrackCount", QUrl::StrictMode ) ),
          xesam_aperture( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#aperture", QUrl::StrictMode ) ),
          xesam_artist( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#artist", QUrl::StrictMode ) ),
          xesam_asText( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#asText", QUrl::StrictMode ) ),
          xesam_aspectRatio( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#aspectRatio", QUrl::StrictMode ) ),
          xesam_attachmentEncoding( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#attachmentEncoding", QUrl::StrictMode ) ),
          xesam_audioBPM( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#audioBPM", QUrl::StrictMode ) ),
          xesam_audioBitrate( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#audioBitrate", QUrl::StrictMode ) ),
          xesam_audioChannels( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#audioChannels", QUrl::StrictMode ) ),
          xesam_audioCodec( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#audioCodec", QUrl::StrictMode ) ),
          xesam_audioCodecType( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#audioCodecType", QUrl::StrictMode ) ),
          xesam_audioSampleBitDepth( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#audioSampleBitDepth", QUrl::StrictMode ) ),
          xesam_audioSampleCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#audioSampleCount", QUrl::StrictMode ) ),
          xesam_audioSampleDataType( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#audioSampleDataType", QUrl::StrictMode ) ),
          xesam_audioSampleRate( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#audioSampleRate", QUrl::StrictMode ) ),
          xesam_author( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#author", QUrl::StrictMode ) ),
          xesam_autoRating( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#autoRating", QUrl::StrictMode ) ),
          xesam_baseRevisionID( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#baseRevisionID", QUrl::StrictMode ) ),
          xesam_bcc( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#bcc", QUrl::StrictMode ) ),
          xesam_birthDate( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#birthDate", QUrl::StrictMode ) ),
          xesam_blogContactURL( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#blogContactURL", QUrl::StrictMode ) ),
          xesam_cameraManufacturer( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#cameraManufacturer", QUrl::StrictMode ) ),
          xesam_cameraModel( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#cameraModel", QUrl::StrictMode ) ),
          xesam_cc( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#cc", QUrl::StrictMode ) ),
          xesam_ccdWidth( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#ccdWidth", QUrl::StrictMode ) ),
          xesam_cellPhoneNumber( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#cellPhoneNumber", QUrl::StrictMode ) ),
          xesam_changeCommitTime( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#changeCommitTime", QUrl::StrictMode ) ),
          xesam_changeCommitter( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#changeCommitter", QUrl::StrictMode ) ),
          xesam_characterCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#characterCount", QUrl::StrictMode ) ),
          xesam_charset( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#charset", QUrl::StrictMode ) ),
          xesam_chatRoom( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#chatRoom", QUrl::StrictMode ) ),
          xesam_colorCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#colorCount", QUrl::StrictMode ) ),
          xesam_colorSpace( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#colorSpace", QUrl::StrictMode ) ),
          xesam_columnCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#columnCount", QUrl::StrictMode ) ),
          xesam_comment( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#comment", QUrl::StrictMode ) ),
          xesam_commentCharacterCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#commentCharacterCount", QUrl::StrictMode ) ),
          xesam_commitDiff( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#commitDiff", QUrl::StrictMode ) ),
          xesam_communicationChannel( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#communicationChannel", QUrl::StrictMode ) ),
          xesam_composer( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#composer", QUrl::StrictMode ) ),
          xesam_compressionAlgorithm( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#compressionAlgorithm", QUrl::StrictMode ) ),
          xesam_compressionLevel( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#compressionLevel", QUrl::StrictMode ) ),
          xesam_conflicts( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#conflicts", QUrl::StrictMode ) ),
          xesam_contactMedium( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#contactMedium", QUrl::StrictMode ) ),
          xesam_contactNick( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#contactNick", QUrl::StrictMode ) ),
          xesam_contactURL( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#contactURL", QUrl::StrictMode ) ),
          xesam_contains( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#contains", QUrl::StrictMode ) ),
          xesam_contentComment( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#contentComment", QUrl::StrictMode ) ),
          xesam_contentCreated( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#contentCreated", QUrl::StrictMode ) ),
          xesam_contentKeyword( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#contentKeyword", QUrl::StrictMode ) ),
          xesam_contentModified( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#contentModified", QUrl::StrictMode ) ),
          xesam_contentType( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#contentType", QUrl::StrictMode ) ),
          xesam_contributor( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#contributor", QUrl::StrictMode ) ),
          xesam_copyright( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#copyright", QUrl::StrictMode ) ),
          xesam_creator( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#creator", QUrl::StrictMode ) ),
          xesam_definesClass( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#definesClass", QUrl::StrictMode ) ),
          xesam_definesFunction( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#definesFunction", QUrl::StrictMode ) ),
          xesam_definesGlobalVariable( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#definesGlobalVariable", QUrl::StrictMode ) ),
          xesam_deletionTime( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#deletionTime", QUrl::StrictMode ) ),
          xesam_depends( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#depends", QUrl::StrictMode ) ),
          xesam_derivedFrom( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#derivedFrom", QUrl::StrictMode ) ),
          xesam_description( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#description", QUrl::StrictMode ) ),
          xesam_discNumber( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#discNumber", QUrl::StrictMode ) ),
          xesam_disclaimer( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#disclaimer", QUrl::StrictMode ) ),
          xesam_documentCategory( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#documentCategory", QUrl::StrictMode ) ),
          xesam_emailAddress( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#emailAddress", QUrl::StrictMode ) ),
          xesam_exposureBias( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#exposureBias", QUrl::StrictMode ) ),
          xesam_exposureProgram( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#exposureProgram", QUrl::StrictMode ) ),
          xesam_exposureTime( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#exposureTime", QUrl::StrictMode ) ),
          xesam_familyName( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#familyName", QUrl::StrictMode ) ),
          xesam_faxPhoneNumber( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#faxPhoneNumber", QUrl::StrictMode ) ),
          xesam_fileExtension( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#fileExtension", QUrl::StrictMode ) ),
          xesam_fileSystemType( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#fileSystemType", QUrl::StrictMode ) ),
          xesam_fingerprint( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#fingerprint", QUrl::StrictMode ) ),
          xesam_firstUsed( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#firstUsed", QUrl::StrictMode ) ),
          xesam_flashUsed( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#flashUsed", QUrl::StrictMode ) ),
          xesam_focalLength( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#focalLength", QUrl::StrictMode ) ),
          xesam_focusDistance( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#focusDistance", QUrl::StrictMode ) ),
          xesam_formatSubtype( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#formatSubtype", QUrl::StrictMode ) ),
          xesam_frameCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#frameCount", QUrl::StrictMode ) ),
          xesam_frameRate( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#frameRate", QUrl::StrictMode ) ),
          xesam_freeSpace( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#freeSpace", QUrl::StrictMode ) ),
          xesam_gender( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#gender", QUrl::StrictMode ) ),
          xesam_generator( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#generator", QUrl::StrictMode ) ),
          xesam_generatorOptions( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#generatorOptions", QUrl::StrictMode ) ),
          xesam_genre( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#genre", QUrl::StrictMode ) ),
          xesam_givenName( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#givenName", QUrl::StrictMode ) ),
          xesam_group( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#group", QUrl::StrictMode ) ),
          xesam_height( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#height", QUrl::StrictMode ) ),
          xesam_homeEmailAddress( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#homeEmailAddress", QUrl::StrictMode ) ),
          xesam_homePhoneNumber( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#homePhoneNumber", QUrl::StrictMode ) ),
          xesam_homePostalAddress( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#homePostalAddress", QUrl::StrictMode ) ),
          xesam_homepageContactURL( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#homepageContactURL", QUrl::StrictMode ) ),
          xesam_honorificPrefix( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#honorificPrefix", QUrl::StrictMode ) ),
          xesam_honorificSuffix( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#honorificSuffix", QUrl::StrictMode ) ),
          xesam_horizontalResolution( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#horizontalResolution", QUrl::StrictMode ) ),
          xesam_id( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#id", QUrl::StrictMode ) ),
          xesam_imContactMedium( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#imContactMedium", QUrl::StrictMode ) ),
          xesam_inReplyTo( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#inReplyTo", QUrl::StrictMode ) ),
          xesam_interest( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#interest", QUrl::StrictMode ) ),
          xesam_interlaceMode( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#interlaceMode", QUrl::StrictMode ) ),
          xesam_ircContactMedium( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#ircContactMedium", QUrl::StrictMode ) ),
          xesam_isContentEncrypted( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#isContentEncrypted", QUrl::StrictMode ) ),
          xesam_isEncrypted( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#isEncrypted", QUrl::StrictMode ) ),
          xesam_isImportant( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#isImportant", QUrl::StrictMode ) ),
          xesam_isInProgress( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#isInProgress", QUrl::StrictMode ) ),
          xesam_isPublicChannel( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#isPublicChannel", QUrl::StrictMode ) ),
          xesam_isRead( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#isRead", QUrl::StrictMode ) ),
          xesam_isSourceEncrypted( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#isSourceEncrypted", QUrl::StrictMode ) ),
          xesam_isoEquivalent( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#isoEquivalent", QUrl::StrictMode ) ),
          xesam_jabberContactMedium( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#jabberContactMedium", QUrl::StrictMode ) ),
          xesam_keyword( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#keyword", QUrl::StrictMode ) ),
          xesam_knows( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#knows", QUrl::StrictMode ) ),
          xesam_language( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#language", QUrl::StrictMode ) ),
          xesam_lastRefreshed( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#lastRefreshed", QUrl::StrictMode ) ),
          xesam_lastUsed( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#lastUsed", QUrl::StrictMode ) ),
          xesam_legal( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#legal", QUrl::StrictMode ) ),
          xesam_license( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#license", QUrl::StrictMode ) ),
          xesam_licenseType( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#licenseType", QUrl::StrictMode ) ),
          xesam_lineCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#lineCount", QUrl::StrictMode ) ),
          xesam_links( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#links", QUrl::StrictMode ) ),
          xesam_localRevision( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#localRevision", QUrl::StrictMode ) ),
          xesam_lyricist( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#lyricist", QUrl::StrictMode ) ),
          xesam_mailingList( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#mailingList", QUrl::StrictMode ) ),
          xesam_mailingPostalAddress( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#mailingPostalAddress", QUrl::StrictMode ) ),
          xesam_maintainer( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#maintainer", QUrl::StrictMode ) ),
          xesam_markupCharacterCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#markupCharacterCount", QUrl::StrictMode ) ),
          xesam_md5Hash( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#md5Hash", QUrl::StrictMode ) ),
          xesam_mediaBitrate( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#mediaBitrate", QUrl::StrictMode ) ),
          xesam_mediaCodec( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#mediaCodec", QUrl::StrictMode ) ),
          xesam_mediaCodecType( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#mediaCodecType", QUrl::StrictMode ) ),
          xesam_mediaDuration( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#mediaDuration", QUrl::StrictMode ) ),
          xesam_mergeConflict( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#mergeConflict", QUrl::StrictMode ) ),
          xesam_meteringMode( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#meteringMode", QUrl::StrictMode ) ),
          xesam_mimeType( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#mimeType", QUrl::StrictMode ) ),
          xesam_mountPoint( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#mountPoint", QUrl::StrictMode ) ),
          xesam_name( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#name", QUrl::StrictMode ) ),
          xesam_newsGroup( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#newsGroup", QUrl::StrictMode ) ),
          xesam_occupiedSpace( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#occupiedSpace", QUrl::StrictMode ) ),
          xesam_orientation( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#orientation", QUrl::StrictMode ) ),
          xesam_originURL( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#originURL", QUrl::StrictMode ) ),
          xesam_originalLocation( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#originalLocation", QUrl::StrictMode ) ),
          xesam_otherName( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#otherName", QUrl::StrictMode ) ),
          xesam_owner( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#owner", QUrl::StrictMode ) ),
          xesam_pageCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#pageCount", QUrl::StrictMode ) ),
          xesam_paragraphCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#paragraphCount", QUrl::StrictMode ) ),
          xesam_performer( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#performer", QUrl::StrictMode ) ),
          xesam_permissions( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#permissions", QUrl::StrictMode ) ),
          xesam_personPhoto( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#personPhoto", QUrl::StrictMode ) ),
          xesam_phoneNumber( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#phoneNumber", QUrl::StrictMode ) ),
          xesam_pixelDataBitDepth( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#pixelDataBitDepth", QUrl::StrictMode ) ),
          xesam_pixelDataType( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#pixelDataType", QUrl::StrictMode ) ),
          xesam_postalAddress( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#postalAddress", QUrl::StrictMode ) ),
          xesam_primaryRecipient( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#primaryRecipient", QUrl::StrictMode ) ),
          xesam_programmingLanguage( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#programmingLanguage", QUrl::StrictMode ) ),
          xesam_receptionTime( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#receptionTime", QUrl::StrictMode ) ),
          xesam_recipient( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#recipient", QUrl::StrictMode ) ),
          xesam_related( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#related", QUrl::StrictMode ) ),
          xesam_remotePassword( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#remotePassword", QUrl::StrictMode ) ),
          xesam_remotePort( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#remotePort", QUrl::StrictMode ) ),
          xesam_remoteServer( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#remoteServer", QUrl::StrictMode ) ),
          xesam_remoteUser( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#remoteUser", QUrl::StrictMode ) ),
          xesam_replyTo( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#replyTo", QUrl::StrictMode ) ),
          xesam_rowCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#rowCount", QUrl::StrictMode ) ),
          xesam_rssFeed( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#rssFeed", QUrl::StrictMode ) ),
          xesam_sampleConfiguration( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#sampleConfiguration", QUrl::StrictMode ) ),
          xesam_sampleDataBitDepth( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#sampleDataBitDepth", QUrl::StrictMode ) ),
          xesam_sampleDataType( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#sampleDataType", QUrl::StrictMode ) ),
          xesam_secondaryRecipient( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#secondaryRecipient", QUrl::StrictMode ) ),
          xesam_seenAttachedAs( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#seenAttachedAs", QUrl::StrictMode ) ),
          xesam_setCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#setCount", QUrl::StrictMode ) ),
          xesam_setRate( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#setRate", QUrl::StrictMode ) ),
          xesam_sha1Hash( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#sha1Hash", QUrl::StrictMode ) ),
          xesam_size( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#size", QUrl::StrictMode ) ),
          xesam_sourceCreated( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#sourceCreated", QUrl::StrictMode ) ),
          xesam_sourceModified( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#sourceModified", QUrl::StrictMode ) ),
          xesam_storageSize( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#storageSize", QUrl::StrictMode ) ),
          xesam_subject( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#subject", QUrl::StrictMode ) ),
          xesam_summary( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#summary", QUrl::StrictMode ) ),
          xesam_supercedes( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#supercedes", QUrl::StrictMode ) ),
          xesam_targetQuality( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#targetQuality", QUrl::StrictMode ) ),
          xesam_title( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#title", QUrl::StrictMode ) ),
          xesam_to( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#to", QUrl::StrictMode ) ),
          xesam_totalSpace( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#totalSpace", QUrl::StrictMode ) ),
          xesam_totalUncompressedSize( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#totalUncompressedSize", QUrl::StrictMode ) ),
          xesam_trackGain( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#trackGain", QUrl::StrictMode ) ),
          xesam_trackNumber( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#trackNumber", QUrl::StrictMode ) ),
          xesam_trackPeakGain( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#trackPeakGain", QUrl::StrictMode ) ),
          xesam_url( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#url", QUrl::StrictMode ) ),
          xesam_useCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#useCount", QUrl::StrictMode ) ),
          xesam_userComment( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#userComment", QUrl::StrictMode ) ),
          xesam_userKeyword( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#userKeyword", QUrl::StrictMode ) ),
          xesam_userRating( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#userRating", QUrl::StrictMode ) ),
          xesam_usesNamespace( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#usesNamespace", QUrl::StrictMode ) ),
          xesam_version( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#version", QUrl::StrictMode ) ),
          xesam_verticalResolution( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#verticalResolution", QUrl::StrictMode ) ),
          xesam_videoBitrate( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#videoBitrate", QUrl::StrictMode ) ),
          xesam_videoCodec( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#videoCodec", QUrl::StrictMode ) ),
          xesam_videoCodecType( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#videoCodecType", QUrl::StrictMode ) ),
          xesam_whiteBalance( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#whiteBalance", QUrl::StrictMode ) ),
          xesam_width( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#width", QUrl::StrictMode ) ),
          xesam_wordCount( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#wordCount", QUrl::StrictMode ) ),
          xesam_workEmailAddress( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#workEmailAddress", QUrl::StrictMode ) ),
          xesam_workPhoneNumber( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#workPhoneNumber", QUrl::StrictMode ) ),
          xesam_workPostalAddress( QUrl::fromEncoded( "http://freedesktop.org/standards/xesam/1.0/core#workPostalAddress", QUrl::StrictMode ) ) {
    }

    QUrl xesam_namespace;
    QUrl xesam_35mmEquivalent;
    QUrl xesam_Annotation;
    QUrl xesam_Archive;
    QUrl xesam_ArchivedFile;
    QUrl xesam_Audio;
    QUrl xesam_AudioList;
    QUrl xesam_BlockDevice;
    QUrl xesam_Bookmark;
    QUrl xesam_CommunicationChannel;
    QUrl xesam_Contact;
    QUrl xesam_ContactGroup;
    QUrl xesam_Content;
    QUrl xesam_DataObject;
    QUrl xesam_DeletedFile;
    QUrl xesam_Document;
    QUrl xesam_Documentation;
    QUrl xesam_Email;
    QUrl xesam_EmailAttachment;
    QUrl xesam_EmbeddedObject;
    QUrl xesam_File;
    QUrl xesam_FileSystem;
    QUrl xesam_Filelike;
    QUrl xesam_Folder;
    QUrl xesam_IMAP4Message;
    QUrl xesam_IMMessage;
    QUrl xesam_Image;
    QUrl xesam_MailingList;
    QUrl xesam_MailingListEmail;
    QUrl xesam_Media;
    QUrl xesam_MediaList;
    QUrl xesam_Message;
    QUrl xesam_MessageboxMessage;
    QUrl xesam_Music;
    QUrl xesam_NewsGroup;
    QUrl xesam_NewsGroupEmail;
    QUrl xesam_OfflineMedia;
    QUrl xesam_Organization;
    QUrl xesam_POP3Message;
    QUrl xesam_Person;
    QUrl xesam_PersonalEmail;
    QUrl xesam_Photo;
    QUrl xesam_Presentation;
    QUrl xesam_Project;
    QUrl xesam_RSSFeed;
    QUrl xesam_RSSMessage;
    QUrl xesam_RemoteFile;
    QUrl xesam_RemoteMessageboxMessage;
    QUrl xesam_RemoteResource;
    QUrl xesam_RevisionControlledFile;
    QUrl xesam_RevisionControlledRepository;
    QUrl xesam_SoftwarePackage;
    QUrl xesam_Source;
    QUrl xesam_SourceCode;
    QUrl xesam_Spreadsheet;
    QUrl xesam_SystemResource;
    QUrl xesam_Tag;
    QUrl xesam_Text;
    QUrl xesam_TextDocument;
    QUrl xesam_UncategorizedText;
    QUrl xesam_Video;
    QUrl xesam_Visual;
    QUrl xesam_XML;
    QUrl xesam_acl;
    QUrl xesam_album;
    QUrl xesam_albumArtist;
    QUrl xesam_albumGain;
    QUrl xesam_albumPeakGain;
    QUrl xesam_albumTrackCount;
    QUrl xesam_aperture;
    QUrl xesam_artist;
    QUrl xesam_asText;
    QUrl xesam_aspectRatio;
    QUrl xesam_attachmentEncoding;
    QUrl xesam_audioBPM;
    QUrl xesam_audioBitrate;
    QUrl xesam_audioChannels;
    QUrl xesam_audioCodec;
    QUrl xesam_audioCodecType;
    QUrl xesam_audioSampleBitDepth;
    QUrl xesam_audioSampleCount;
    QUrl xesam_audioSampleDataType;
    QUrl xesam_audioSampleRate;
    QUrl xesam_author;
    QUrl xesam_autoRating;
    QUrl xesam_baseRevisionID;
    QUrl xesam_bcc;
    QUrl xesam_birthDate;
    QUrl xesam_blogContactURL;
    QUrl xesam_cameraManufacturer;
    QUrl xesam_cameraModel;
    QUrl xesam_cc;
    QUrl xesam_ccdWidth;
    QUrl xesam_cellPhoneNumber;
    QUrl xesam_changeCommitTime;
    QUrl xesam_changeCommitter;
    QUrl xesam_characterCount;
    QUrl xesam_charset;
    QUrl xesam_chatRoom;
    QUrl xesam_colorCount;
    QUrl xesam_colorSpace;
    QUrl xesam_columnCount;
    QUrl xesam_comment;
    QUrl xesam_commentCharacterCount;
    QUrl xesam_commitDiff;
    QUrl xesam_communicationChannel;
    QUrl xesam_composer;
    QUrl xesam_compressionAlgorithm;
    QUrl xesam_compressionLevel;
    QUrl xesam_conflicts;
    QUrl xesam_contactMedium;
    QUrl xesam_contactNick;
    QUrl xesam_contactURL;
    QUrl xesam_contains;
    QUrl xesam_contentComment;
    QUrl xesam_contentCreated;
    QUrl xesam_contentKeyword;
    QUrl xesam_contentModified;
    QUrl xesam_contentType;
    QUrl xesam_contributor;
    QUrl xesam_copyright;
    QUrl xesam_creator;
    QUrl xesam_definesClass;
    QUrl xesam_definesFunction;
    QUrl xesam_definesGlobalVariable;
    QUrl xesam_deletionTime;
    QUrl xesam_depends;
    QUrl xesam_derivedFrom;
    QUrl xesam_description;
    QUrl xesam_discNumber;
    QUrl xesam_disclaimer;
    QUrl xesam_documentCategory;
    QUrl xesam_emailAddress;
    QUrl xesam_exposureBias;
    QUrl xesam_exposureProgram;
    QUrl xesam_exposureTime;
    QUrl xesam_familyName;
    QUrl xesam_faxPhoneNumber;
    QUrl xesam_fileExtension;
    QUrl xesam_fileSystemType;
    QUrl xesam_fingerprint;
    QUrl xesam_firstUsed;
    QUrl xesam_flashUsed;
    QUrl xesam_focalLength;
    QUrl xesam_focusDistance;
    QUrl xesam_formatSubtype;
    QUrl xesam_frameCount;
    QUrl xesam_frameRate;
    QUrl xesam_freeSpace;
    QUrl xesam_gender;
    QUrl xesam_generator;
    QUrl xesam_generatorOptions;
    QUrl xesam_genre;
    QUrl xesam_givenName;
    QUrl xesam_group;
    QUrl xesam_height;
    QUrl xesam_homeEmailAddress;
    QUrl xesam_homePhoneNumber;
    QUrl xesam_homePostalAddress;
    QUrl xesam_homepageContactURL;
    QUrl xesam_honorificPrefix;
    QUrl xesam_honorificSuffix;
    QUrl xesam_horizontalResolution;
    QUrl xesam_id;
    QUrl xesam_imContactMedium;
    QUrl xesam_inReplyTo;
    QUrl xesam_interest;
    QUrl xesam_interlaceMode;
    QUrl xesam_ircContactMedium;
    QUrl xesam_isContentEncrypted;
    QUrl xesam_isEncrypted;
    QUrl xesam_isImportant;
    QUrl xesam_isInProgress;
    QUrl xesam_isPublicChannel;
    QUrl xesam_isRead;
    QUrl xesam_isSourceEncrypted;
    QUrl xesam_isoEquivalent;
    QUrl xesam_jabberContactMedium;
    QUrl xesam_keyword;
    QUrl xesam_knows;
    QUrl xesam_language;
    QUrl xesam_lastRefreshed;
    QUrl xesam_lastUsed;
    QUrl xesam_legal;
    QUrl xesam_license;
    QUrl xesam_licenseType;
    QUrl xesam_lineCount;
    QUrl xesam_links;
    QUrl xesam_localRevision;
    QUrl xesam_lyricist;
    QUrl xesam_mailingList;
    QUrl xesam_mailingPostalAddress;
    QUrl xesam_maintainer;
    QUrl xesam_markupCharacterCount;
    QUrl xesam_md5Hash;
    QUrl xesam_mediaBitrate;
    QUrl xesam_mediaCodec;
    QUrl xesam_mediaCodecType;
    QUrl xesam_mediaDuration;
    QUrl xesam_mergeConflict;
    QUrl xesam_meteringMode;
    QUrl xesam_mimeType;
    QUrl xesam_mountPoint;
    QUrl xesam_name;
    QUrl xesam_newsGroup;
    QUrl xesam_occupiedSpace;
    QUrl xesam_orientation;
    QUrl xesam_originURL;
    QUrl xesam_originalLocation;
    QUrl xesam_otherName;
    QUrl xesam_owner;
    QUrl xesam_pageCount;
    QUrl xesam_paragraphCount;
    QUrl xesam_performer;
    QUrl xesam_permissions;
    QUrl xesam_personPhoto;
    QUrl xesam_phoneNumber;
    QUrl xesam_pixelDataBitDepth;
    QUrl xesam_pixelDataType;
    QUrl xesam_postalAddress;
    QUrl xesam_primaryRecipient;
    QUrl xesam_programmingLanguage;
    QUrl xesam_receptionTime;
    QUrl xesam_recipient;
    QUrl xesam_related;
    QUrl xesam_remotePassword;
    QUrl xesam_remotePort;
    QUrl xesam_remoteServer;
    QUrl xesam_remoteUser;
    QUrl xesam_replyTo;
    QUrl xesam_rowCount;
    QUrl xesam_rssFeed;
    QUrl xesam_sampleConfiguration;
    QUrl xesam_sampleDataBitDepth;
    QUrl xesam_sampleDataType;
    QUrl xesam_secondaryRecipient;
    QUrl xesam_seenAttachedAs;
    QUrl xesam_setCount;
    QUrl xesam_setRate;
    QUrl xesam_sha1Hash;
    QUrl xesam_size;
    QUrl xesam_sourceCreated;
    QUrl xesam_sourceModified;
    QUrl xesam_storageSize;
    QUrl xesam_subject;
    QUrl xesam_summary;
    QUrl xesam_supercedes;
    QUrl xesam_targetQuality;
    QUrl xesam_title;
    QUrl xesam_to;
    QUrl xesam_totalSpace;
    QUrl xesam_totalUncompressedSize;
    QUrl xesam_trackGain;
    QUrl xesam_trackNumber;
    QUrl xesam_trackPeakGain;
    QUrl xesam_url;
    QUrl xesam_useCount;
    QUrl xesam_userComment;
    QUrl xesam_userKeyword;
    QUrl xesam_userRating;
    QUrl xesam_usesNamespace;
    QUrl xesam_version;
    QUrl xesam_verticalResolution;
    QUrl xesam_videoBitrate;
    QUrl xesam_videoCodec;
    QUrl xesam_videoCodecType;
    QUrl xesam_whiteBalance;
    QUrl xesam_width;
    QUrl xesam_wordCount;
    QUrl xesam_workEmailAddress;
    QUrl xesam_workPhoneNumber;
    QUrl xesam_workPostalAddress;
};

QThreadStorage<XesamPrivate*> qts_xesam;
XesamPrivate* s_xesam() {
    if( !qts_xesam.hasLocalData() )
        qts_xesam.setLocalData( new XesamPrivate );
    return qts_xesam.localData();
}

QUrl Soprano::Vocabulary::Xesam::xesamNamespace()
{
    return s_xesam()->xesam_namespace;
}

QUrl Soprano::Vocabulary::Xesam::xesam35mmEquivalent()
{
    return s_xesam()->xesam_35mmEquivalent;
}

QUrl Soprano::Vocabulary::Xesam::Annotation()
{
    return s_xesam()->xesam_Annotation;
}

QUrl Soprano::Vocabulary::Xesam::Archive()
{
    return s_xesam()->xesam_Archive;
}

QUrl Soprano::Vocabulary::Xesam::ArchivedFile()
{
    return s_xesam()->xesam_ArchivedFile;
}

QUrl Soprano::Vocabulary::Xesam::Audio()
{
    return s_xesam()->xesam_Audio;
}

QUrl Soprano::Vocabulary::Xesam::AudioList()
{
    return s_xesam()->xesam_AudioList;
}

QUrl Soprano::Vocabulary::Xesam::BlockDevice()
{
    return s_xesam()->xesam_BlockDevice;
}

QUrl Soprano::Vocabulary::Xesam::Bookmark()
{
    return s_xesam()->xesam_Bookmark;
}

QUrl Soprano::Vocabulary::Xesam::CommunicationChannel()
{
    return s_xesam()->xesam_CommunicationChannel;
}

QUrl Soprano::Vocabulary::Xesam::Contact()
{
    return s_xesam()->xesam_Contact;
}

QUrl Soprano::Vocabulary::Xesam::ContactGroup()
{
    return s_xesam()->xesam_ContactGroup;
}

QUrl Soprano::Vocabulary::Xesam::Content()
{
    return s_xesam()->xesam_Content;
}

QUrl Soprano::Vocabulary::Xesam::DataObject()
{
    return s_xesam()->xesam_DataObject;
}

QUrl Soprano::Vocabulary::Xesam::DeletedFile()
{
    return s_xesam()->xesam_DeletedFile;
}

QUrl Soprano::Vocabulary::Xesam::Document()
{
    return s_xesam()->xesam_Document;
}

QUrl Soprano::Vocabulary::Xesam::Documentation()
{
    return s_xesam()->xesam_Documentation;
}

QUrl Soprano::Vocabulary::Xesam::Email()
{
    return s_xesam()->xesam_Email;
}

QUrl Soprano::Vocabulary::Xesam::EmailAttachment()
{
    return s_xesam()->xesam_EmailAttachment;
}

QUrl Soprano::Vocabulary::Xesam::EmbeddedObject()
{
    return s_xesam()->xesam_EmbeddedObject;
}

QUrl Soprano::Vocabulary::Xesam::File()
{
    return s_xesam()->xesam_File;
}

QUrl Soprano::Vocabulary::Xesam::FileSystem()
{
    return s_xesam()->xesam_FileSystem;
}

QUrl Soprano::Vocabulary::Xesam::Filelike()
{
    return s_xesam()->xesam_Filelike;
}

QUrl Soprano::Vocabulary::Xesam::Folder()
{
    return s_xesam()->xesam_Folder;
}

QUrl Soprano::Vocabulary::Xesam::IMAP4Message()
{
    return s_xesam()->xesam_IMAP4Message;
}

QUrl Soprano::Vocabulary::Xesam::IMMessage()
{
    return s_xesam()->xesam_IMMessage;
}

QUrl Soprano::Vocabulary::Xesam::Image()
{
    return s_xesam()->xesam_Image;
}

QUrl Soprano::Vocabulary::Xesam::MailingList()
{
    return s_xesam()->xesam_MailingList;
}

QUrl Soprano::Vocabulary::Xesam::MailingListEmail()
{
    return s_xesam()->xesam_MailingListEmail;
}

QUrl Soprano::Vocabulary::Xesam::Media()
{
    return s_xesam()->xesam_Media;
}

QUrl Soprano::Vocabulary::Xesam::MediaList()
{
    return s_xesam()->xesam_MediaList;
}

QUrl Soprano::Vocabulary::Xesam::Message()
{
    return s_xesam()->xesam_Message;
}

QUrl Soprano::Vocabulary::Xesam::MessageboxMessage()
{
    return s_xesam()->xesam_MessageboxMessage;
}

QUrl Soprano::Vocabulary::Xesam::Music()
{
    return s_xesam()->xesam_Music;
}

QUrl Soprano::Vocabulary::Xesam::NewsGroup()
{
    return s_xesam()->xesam_NewsGroup;
}

QUrl Soprano::Vocabulary::Xesam::NewsGroupEmail()
{
    return s_xesam()->xesam_NewsGroupEmail;
}

QUrl Soprano::Vocabulary::Xesam::OfflineMedia()
{
    return s_xesam()->xesam_OfflineMedia;
}

QUrl Soprano::Vocabulary::Xesam::Organization()
{
    return s_xesam()->xesam_Organization;
}

QUrl Soprano::Vocabulary::Xesam::POP3Message()
{
    return s_xesam()->xesam_POP3Message;
}

QUrl Soprano::Vocabulary::Xesam::Person()
{
    return s_xesam()->xesam_Person;
}

QUrl Soprano::Vocabulary::Xesam::PersonalEmail()
{
    return s_xesam()->xesam_PersonalEmail;
}

QUrl Soprano::Vocabulary::Xesam::Photo()
{
    return s_xesam()->xesam_Photo;
}

QUrl Soprano::Vocabulary::Xesam::Presentation()
{
    return s_xesam()->xesam_Presentation;
}

QUrl Soprano::Vocabulary::Xesam::Project()
{
    return s_xesam()->xesam_Project;
}

QUrl Soprano::Vocabulary::Xesam::RSSFeed()
{
    return s_xesam()->xesam_RSSFeed;
}

QUrl Soprano::Vocabulary::Xesam::RSSMessage()
{
    return s_xesam()->xesam_RSSMessage;
}

QUrl Soprano::Vocabulary::Xesam::RemoteFile()
{
    return s_xesam()->xesam_RemoteFile;
}

QUrl Soprano::Vocabulary::Xesam::RemoteMessageboxMessage()
{
    return s_xesam()->xesam_RemoteMessageboxMessage;
}

QUrl Soprano::Vocabulary::Xesam::RemoteResource()
{
    return s_xesam()->xesam_RemoteResource;
}

QUrl Soprano::Vocabulary::Xesam::RevisionControlledFile()
{
    return s_xesam()->xesam_RevisionControlledFile;
}

QUrl Soprano::Vocabulary::Xesam::RevisionControlledRepository()
{
    return s_xesam()->xesam_RevisionControlledRepository;
}

QUrl Soprano::Vocabulary::Xesam::SoftwarePackage()
{
    return s_xesam()->xesam_SoftwarePackage;
}

QUrl Soprano::Vocabulary::Xesam::Source()
{
    return s_xesam()->xesam_Source;
}

QUrl Soprano::Vocabulary::Xesam::SourceCode()
{
    return s_xesam()->xesam_SourceCode;
}

QUrl Soprano::Vocabulary::Xesam::Spreadsheet()
{
    return s_xesam()->xesam_Spreadsheet;
}

QUrl Soprano::Vocabulary::Xesam::SystemResource()
{
    return s_xesam()->xesam_SystemResource;
}

QUrl Soprano::Vocabulary::Xesam::Tag()
{
    return s_xesam()->xesam_Tag;
}

QUrl Soprano::Vocabulary::Xesam::Text()
{
    return s_xesam()->xesam_Text;
}

QUrl Soprano::Vocabulary::Xesam::TextDocument()
{
    return s_xesam()->xesam_TextDocument;
}

QUrl Soprano::Vocabulary::Xesam::UncategorizedText()
{
    return s_xesam()->xesam_UncategorizedText;
}

QUrl Soprano::Vocabulary::Xesam::Video()
{
    return s_xesam()->xesam_Video;
}

QUrl Soprano::Vocabulary::Xesam::Visual()
{
    return s_xesam()->xesam_Visual;
}

QUrl Soprano::Vocabulary::Xesam::XML()
{
    return s_xesam()->xesam_XML;
}

QUrl Soprano::Vocabulary::Xesam::acl()
{
    return s_xesam()->xesam_acl;
}

QUrl Soprano::Vocabulary::Xesam::album()
{
    return s_xesam()->xesam_album;
}

QUrl Soprano::Vocabulary::Xesam::albumArtist()
{
    return s_xesam()->xesam_albumArtist;
}

QUrl Soprano::Vocabulary::Xesam::albumGain()
{
    return s_xesam()->xesam_albumGain;
}

QUrl Soprano::Vocabulary::Xesam::albumPeakGain()
{
    return s_xesam()->xesam_albumPeakGain;
}

QUrl Soprano::Vocabulary::Xesam::albumTrackCount()
{
    return s_xesam()->xesam_albumTrackCount;
}

QUrl Soprano::Vocabulary::Xesam::aperture()
{
    return s_xesam()->xesam_aperture;
}

QUrl Soprano::Vocabulary::Xesam::artist()
{
    return s_xesam()->xesam_artist;
}

QUrl Soprano::Vocabulary::Xesam::asText()
{
    return s_xesam()->xesam_asText;
}

QUrl Soprano::Vocabulary::Xesam::aspectRatio()
{
    return s_xesam()->xesam_aspectRatio;
}

QUrl Soprano::Vocabulary::Xesam::attachmentEncoding()
{
    return s_xesam()->xesam_attachmentEncoding;
}

QUrl Soprano::Vocabulary::Xesam::audioBPM()
{
    return s_xesam()->xesam_audioBPM;
}

QUrl Soprano::Vocabulary::Xesam::audioBitrate()
{
    return s_xesam()->xesam_audioBitrate;
}

QUrl Soprano::Vocabulary::Xesam::audioChannels()
{
    return s_xesam()->xesam_audioChannels;
}

QUrl Soprano::Vocabulary::Xesam::audioCodec()
{
    return s_xesam()->xesam_audioCodec;
}

QUrl Soprano::Vocabulary::Xesam::audioCodecType()
{
    return s_xesam()->xesam_audioCodecType;
}

QUrl Soprano::Vocabulary::Xesam::audioSampleBitDepth()
{
    return s_xesam()->xesam_audioSampleBitDepth;
}

QUrl Soprano::Vocabulary::Xesam::audioSampleCount()
{
    return s_xesam()->xesam_audioSampleCount;
}

QUrl Soprano::Vocabulary::Xesam::audioSampleDataType()
{
    return s_xesam()->xesam_audioSampleDataType;
}

QUrl Soprano::Vocabulary::Xesam::audioSampleRate()
{
    return s_xesam()->xesam_audioSampleRate;
}

QUrl Soprano::Vocabulary::Xesam::author()
{
    return s_xesam()->xesam_author;
}

QUrl Soprano::Vocabulary::Xesam::autoRating()
{
    return s_xesam()->xesam_autoRating;
}

QUrl Soprano::Vocabulary::Xesam::baseRevisionID()
{
    return s_xesam()->xesam_baseRevisionID;
}

QUrl Soprano::Vocabulary::Xesam::bcc()
{
    return s_xesam()->xesam_bcc;
}

QUrl Soprano::Vocabulary::Xesam::birthDate()
{
    return s_xesam()->xesam_birthDate;
}

QUrl Soprano::Vocabulary::Xesam::blogContactURL()
{
    return s_xesam()->xesam_blogContactURL;
}

QUrl Soprano::Vocabulary::Xesam::cameraManufacturer()
{
    return s_xesam()->xesam_cameraManufacturer;
}

QUrl Soprano::Vocabulary::Xesam::cameraModel()
{
    return s_xesam()->xesam_cameraModel;
}

QUrl Soprano::Vocabulary::Xesam::cc()
{
    return s_xesam()->xesam_cc;
}

QUrl Soprano::Vocabulary::Xesam::ccdWidth()
{
    return s_xesam()->xesam_ccdWidth;
}

QUrl Soprano::Vocabulary::Xesam::cellPhoneNumber()
{
    return s_xesam()->xesam_cellPhoneNumber;
}

QUrl Soprano::Vocabulary::Xesam::changeCommitTime()
{
    return s_xesam()->xesam_changeCommitTime;
}

QUrl Soprano::Vocabulary::Xesam::changeCommitter()
{
    return s_xesam()->xesam_changeCommitter;
}

QUrl Soprano::Vocabulary::Xesam::characterCount()
{
    return s_xesam()->xesam_characterCount;
}

QUrl Soprano::Vocabulary::Xesam::charset()
{
    return s_xesam()->xesam_charset;
}

QUrl Soprano::Vocabulary::Xesam::chatRoom()
{
    return s_xesam()->xesam_chatRoom;
}

QUrl Soprano::Vocabulary::Xesam::colorCount()
{
    return s_xesam()->xesam_colorCount;
}

QUrl Soprano::Vocabulary::Xesam::colorSpace()
{
    return s_xesam()->xesam_colorSpace;
}

QUrl Soprano::Vocabulary::Xesam::columnCount()
{
    return s_xesam()->xesam_columnCount;
}

QUrl Soprano::Vocabulary::Xesam::comment()
{
    return s_xesam()->xesam_comment;
}

QUrl Soprano::Vocabulary::Xesam::commentCharacterCount()
{
    return s_xesam()->xesam_commentCharacterCount;
}

QUrl Soprano::Vocabulary::Xesam::commitDiff()
{
    return s_xesam()->xesam_commitDiff;
}

QUrl Soprano::Vocabulary::Xesam::communicationChannel()
{
    return s_xesam()->xesam_communicationChannel;
}

QUrl Soprano::Vocabulary::Xesam::composer()
{
    return s_xesam()->xesam_composer;
}

QUrl Soprano::Vocabulary::Xesam::compressionAlgorithm()
{
    return s_xesam()->xesam_compressionAlgorithm;
}

QUrl Soprano::Vocabulary::Xesam::compressionLevel()
{
    return s_xesam()->xesam_compressionLevel;
}

QUrl Soprano::Vocabulary::Xesam::conflicts()
{
    return s_xesam()->xesam_conflicts;
}

QUrl Soprano::Vocabulary::Xesam::contactMedium()
{
    return s_xesam()->xesam_contactMedium;
}

QUrl Soprano::Vocabulary::Xesam::contactNick()
{
    return s_xesam()->xesam_contactNick;
}

QUrl Soprano::Vocabulary::Xesam::contactURL()
{
    return s_xesam()->xesam_contactURL;
}

QUrl Soprano::Vocabulary::Xesam::contains()
{
    return s_xesam()->xesam_contains;
}

QUrl Soprano::Vocabulary::Xesam::contentComment()
{
    return s_xesam()->xesam_contentComment;
}

QUrl Soprano::Vocabulary::Xesam::contentCreated()
{
    return s_xesam()->xesam_contentCreated;
}

QUrl Soprano::Vocabulary::Xesam::contentKeyword()
{
    return s_xesam()->xesam_contentKeyword;
}

QUrl Soprano::Vocabulary::Xesam::contentModified()
{
    return s_xesam()->xesam_contentModified;
}

QUrl Soprano::Vocabulary::Xesam::contentType()
{
    return s_xesam()->xesam_contentType;
}

QUrl Soprano::Vocabulary::Xesam::contributor()
{
    return s_xesam()->xesam_contributor;
}

QUrl Soprano::Vocabulary::Xesam::copyright()
{
    return s_xesam()->xesam_copyright;
}

QUrl Soprano::Vocabulary::Xesam::creator()
{
    return s_xesam()->xesam_creator;
}

QUrl Soprano::Vocabulary::Xesam::definesClass()
{
    return s_xesam()->xesam_definesClass;
}

QUrl Soprano::Vocabulary::Xesam::definesFunction()
{
    return s_xesam()->xesam_definesFunction;
}

QUrl Soprano::Vocabulary::Xesam::definesGlobalVariable()
{
    return s_xesam()->xesam_definesGlobalVariable;
}

QUrl Soprano::Vocabulary::Xesam::deletionTime()
{
    return s_xesam()->xesam_deletionTime;
}

QUrl Soprano::Vocabulary::Xesam::depends()
{
    return s_xesam()->xesam_depends;
}

QUrl Soprano::Vocabulary::Xesam::derivedFrom()
{
    return s_xesam()->xesam_derivedFrom;
}

QUrl Soprano::Vocabulary::Xesam::description()
{
    return s_xesam()->xesam_description;
}

QUrl Soprano::Vocabulary::Xesam::discNumber()
{
    return s_xesam()->xesam_discNumber;
}

QUrl Soprano::Vocabulary::Xesam::disclaimer()
{
    return s_xesam()->xesam_disclaimer;
}

QUrl Soprano::Vocabulary::Xesam::documentCategory()
{
    return s_xesam()->xesam_documentCategory;
}

QUrl Soprano::Vocabulary::Xesam::emailAddress()
{
    return s_xesam()->xesam_emailAddress;
}

QUrl Soprano::Vocabulary::Xesam::exposureBias()
{
    return s_xesam()->xesam_exposureBias;
}

QUrl Soprano::Vocabulary::Xesam::exposureProgram()
{
    return s_xesam()->xesam_exposureProgram;
}

QUrl Soprano::Vocabulary::Xesam::exposureTime()
{
    return s_xesam()->xesam_exposureTime;
}

QUrl Soprano::Vocabulary::Xesam::familyName()
{
    return s_xesam()->xesam_familyName;
}

QUrl Soprano::Vocabulary::Xesam::faxPhoneNumber()
{
    return s_xesam()->xesam_faxPhoneNumber;
}

QUrl Soprano::Vocabulary::Xesam::fileExtension()
{
    return s_xesam()->xesam_fileExtension;
}

QUrl Soprano::Vocabulary::Xesam::fileSystemType()
{
    return s_xesam()->xesam_fileSystemType;
}

QUrl Soprano::Vocabulary::Xesam::fingerprint()
{
    return s_xesam()->xesam_fingerprint;
}

QUrl Soprano::Vocabulary::Xesam::firstUsed()
{
    return s_xesam()->xesam_firstUsed;
}

QUrl Soprano::Vocabulary::Xesam::flashUsed()
{
    return s_xesam()->xesam_flashUsed;
}

QUrl Soprano::Vocabulary::Xesam::focalLength()
{
    return s_xesam()->xesam_focalLength;
}

QUrl Soprano::Vocabulary::Xesam::focusDistance()
{
    return s_xesam()->xesam_focusDistance;
}

QUrl Soprano::Vocabulary::Xesam::formatSubtype()
{
    return s_xesam()->xesam_formatSubtype;
}

QUrl Soprano::Vocabulary::Xesam::frameCount()
{
    return s_xesam()->xesam_frameCount;
}

QUrl Soprano::Vocabulary::Xesam::frameRate()
{
    return s_xesam()->xesam_frameRate;
}

QUrl Soprano::Vocabulary::Xesam::freeSpace()
{
    return s_xesam()->xesam_freeSpace;
}

QUrl Soprano::Vocabulary::Xesam::gender()
{
    return s_xesam()->xesam_gender;
}

QUrl Soprano::Vocabulary::Xesam::generator()
{
    return s_xesam()->xesam_generator;
}

QUrl Soprano::Vocabulary::Xesam::generatorOptions()
{
    return s_xesam()->xesam_generatorOptions;
}

QUrl Soprano::Vocabulary::Xesam::genre()
{
    return s_xesam()->xesam_genre;
}

QUrl Soprano::Vocabulary::Xesam::givenName()
{
    return s_xesam()->xesam_givenName;
}

QUrl Soprano::Vocabulary::Xesam::group()
{
    return s_xesam()->xesam_group;
}

QUrl Soprano::Vocabulary::Xesam::height()
{
    return s_xesam()->xesam_height;
}

QUrl Soprano::Vocabulary::Xesam::homeEmailAddress()
{
    return s_xesam()->xesam_homeEmailAddress;
}

QUrl Soprano::Vocabulary::Xesam::homePhoneNumber()
{
    return s_xesam()->xesam_homePhoneNumber;
}

QUrl Soprano::Vocabulary::Xesam::homePostalAddress()
{
    return s_xesam()->xesam_homePostalAddress;
}

QUrl Soprano::Vocabulary::Xesam::homepageContactURL()
{
    return s_xesam()->xesam_homepageContactURL;
}

QUrl Soprano::Vocabulary::Xesam::honorificPrefix()
{
    return s_xesam()->xesam_honorificPrefix;
}

QUrl Soprano::Vocabulary::Xesam::honorificSuffix()
{
    return s_xesam()->xesam_honorificSuffix;
}

QUrl Soprano::Vocabulary::Xesam::horizontalResolution()
{
    return s_xesam()->xesam_horizontalResolution;
}

QUrl Soprano::Vocabulary::Xesam::id()
{
    return s_xesam()->xesam_id;
}

QUrl Soprano::Vocabulary::Xesam::imContactMedium()
{
    return s_xesam()->xesam_imContactMedium;
}

QUrl Soprano::Vocabulary::Xesam::inReplyTo()
{
    return s_xesam()->xesam_inReplyTo;
}

QUrl Soprano::Vocabulary::Xesam::interest()
{
    return s_xesam()->xesam_interest;
}

QUrl Soprano::Vocabulary::Xesam::interlaceMode()
{
    return s_xesam()->xesam_interlaceMode;
}

QUrl Soprano::Vocabulary::Xesam::ircContactMedium()
{
    return s_xesam()->xesam_ircContactMedium;
}

QUrl Soprano::Vocabulary::Xesam::isContentEncrypted()
{
    return s_xesam()->xesam_isContentEncrypted;
}

QUrl Soprano::Vocabulary::Xesam::isEncrypted()
{
    return s_xesam()->xesam_isEncrypted;
}

QUrl Soprano::Vocabulary::Xesam::isImportant()
{
    return s_xesam()->xesam_isImportant;
}

QUrl Soprano::Vocabulary::Xesam::isInProgress()
{
    return s_xesam()->xesam_isInProgress;
}

QUrl Soprano::Vocabulary::Xesam::isPublicChannel()
{
    return s_xesam()->xesam_isPublicChannel;
}

QUrl Soprano::Vocabulary::Xesam::isRead()
{
    return s_xesam()->xesam_isRead;
}

QUrl Soprano::Vocabulary::Xesam::isSourceEncrypted()
{
    return s_xesam()->xesam_isSourceEncrypted;
}

QUrl Soprano::Vocabulary::Xesam::isoEquivalent()
{
    return s_xesam()->xesam_isoEquivalent;
}

QUrl Soprano::Vocabulary::Xesam::jabberContactMedium()
{
    return s_xesam()->xesam_jabberContactMedium;
}

QUrl Soprano::Vocabulary::Xesam::keyword()
{
    return s_xesam()->xesam_keyword;
}

QUrl Soprano::Vocabulary::Xesam::knows()
{
    return s_xesam()->xesam_knows;
}

QUrl Soprano::Vocabulary::Xesam::language()
{
    return s_xesam()->xesam_language;
}

QUrl Soprano::Vocabulary::Xesam::lastRefreshed()
{
    return s_xesam()->xesam_lastRefreshed;
}

QUrl Soprano::Vocabulary::Xesam::lastUsed()
{
    return s_xesam()->xesam_lastUsed;
}

QUrl Soprano::Vocabulary::Xesam::legal()
{
    return s_xesam()->xesam_legal;
}

QUrl Soprano::Vocabulary::Xesam::license()
{
    return s_xesam()->xesam_license;
}

QUrl Soprano::Vocabulary::Xesam::licenseType()
{
    return s_xesam()->xesam_licenseType;
}

QUrl Soprano::Vocabulary::Xesam::lineCount()
{
    return s_xesam()->xesam_lineCount;
}

QUrl Soprano::Vocabulary::Xesam::links()
{
    return s_xesam()->xesam_links;
}

QUrl Soprano::Vocabulary::Xesam::localRevision()
{
    return s_xesam()->xesam_localRevision;
}

QUrl Soprano::Vocabulary::Xesam::lyricist()
{
    return s_xesam()->xesam_lyricist;
}

QUrl Soprano::Vocabulary::Xesam::mailingList()
{
    return s_xesam()->xesam_mailingList;
}

QUrl Soprano::Vocabulary::Xesam::mailingPostalAddress()
{
    return s_xesam()->xesam_mailingPostalAddress;
}

QUrl Soprano::Vocabulary::Xesam::maintainer()
{
    return s_xesam()->xesam_maintainer;
}

QUrl Soprano::Vocabulary::Xesam::markupCharacterCount()
{
    return s_xesam()->xesam_markupCharacterCount;
}

QUrl Soprano::Vocabulary::Xesam::md5Hash()
{
    return s_xesam()->xesam_md5Hash;
}

QUrl Soprano::Vocabulary::Xesam::mediaBitrate()
{
    return s_xesam()->xesam_mediaBitrate;
}

QUrl Soprano::Vocabulary::Xesam::mediaCodec()
{
    return s_xesam()->xesam_mediaCodec;
}

QUrl Soprano::Vocabulary::Xesam::mediaCodecType()
{
    return s_xesam()->xesam_mediaCodecType;
}

QUrl Soprano::Vocabulary::Xesam::mediaDuration()
{
    return s_xesam()->xesam_mediaDuration;
}

QUrl Soprano::Vocabulary::Xesam::mergeConflict()
{
    return s_xesam()->xesam_mergeConflict;
}

QUrl Soprano::Vocabulary::Xesam::meteringMode()
{
    return s_xesam()->xesam_meteringMode;
}

QUrl Soprano::Vocabulary::Xesam::mimeType()
{
    return s_xesam()->xesam_mimeType;
}

QUrl Soprano::Vocabulary::Xesam::mountPoint()
{
    return s_xesam()->xesam_mountPoint;
}

QUrl Soprano::Vocabulary::Xesam::name()
{
    return s_xesam()->xesam_name;
}

QUrl Soprano::Vocabulary::Xesam::newsGroup()
{
    return s_xesam()->xesam_newsGroup;
}

QUrl Soprano::Vocabulary::Xesam::occupiedSpace()
{
    return s_xesam()->xesam_occupiedSpace;
}

QUrl Soprano::Vocabulary::Xesam::orientation()
{
    return s_xesam()->xesam_orientation;
}

QUrl Soprano::Vocabulary::Xesam::originURL()
{
    return s_xesam()->xesam_originURL;
}

QUrl Soprano::Vocabulary::Xesam::originalLocation()
{
    return s_xesam()->xesam_originalLocation;
}

QUrl Soprano::Vocabulary::Xesam::otherName()
{
    return s_xesam()->xesam_otherName;
}

QUrl Soprano::Vocabulary::Xesam::owner()
{
    return s_xesam()->xesam_owner;
}

QUrl Soprano::Vocabulary::Xesam::pageCount()
{
    return s_xesam()->xesam_pageCount;
}

QUrl Soprano::Vocabulary::Xesam::paragraphCount()
{
    return s_xesam()->xesam_paragraphCount;
}

QUrl Soprano::Vocabulary::Xesam::performer()
{
    return s_xesam()->xesam_performer;
}

QUrl Soprano::Vocabulary::Xesam::permissions()
{
    return s_xesam()->xesam_permissions;
}

QUrl Soprano::Vocabulary::Xesam::personPhoto()
{
    return s_xesam()->xesam_personPhoto;
}

QUrl Soprano::Vocabulary::Xesam::phoneNumber()
{
    return s_xesam()->xesam_phoneNumber;
}

QUrl Soprano::Vocabulary::Xesam::pixelDataBitDepth()
{
    return s_xesam()->xesam_pixelDataBitDepth;
}

QUrl Soprano::Vocabulary::Xesam::pixelDataType()
{
    return s_xesam()->xesam_pixelDataType;
}

QUrl Soprano::Vocabulary::Xesam::postalAddress()
{
    return s_xesam()->xesam_postalAddress;
}

QUrl Soprano::Vocabulary::Xesam::primaryRecipient()
{
    return s_xesam()->xesam_primaryRecipient;
}

QUrl Soprano::Vocabulary::Xesam::programmingLanguage()
{
    return s_xesam()->xesam_programmingLanguage;
}

QUrl Soprano::Vocabulary::Xesam::receptionTime()
{
    return s_xesam()->xesam_receptionTime;
}

QUrl Soprano::Vocabulary::Xesam::recipient()
{
    return s_xesam()->xesam_recipient;
}

QUrl Soprano::Vocabulary::Xesam::related()
{
    return s_xesam()->xesam_related;
}

QUrl Soprano::Vocabulary::Xesam::remotePassword()
{
    return s_xesam()->xesam_remotePassword;
}

QUrl Soprano::Vocabulary::Xesam::remotePort()
{
    return s_xesam()->xesam_remotePort;
}

QUrl Soprano::Vocabulary::Xesam::remoteServer()
{
    return s_xesam()->xesam_remoteServer;
}

QUrl Soprano::Vocabulary::Xesam::remoteUser()
{
    return s_xesam()->xesam_remoteUser;
}

QUrl Soprano::Vocabulary::Xesam::replyTo()
{
    return s_xesam()->xesam_replyTo;
}

QUrl Soprano::Vocabulary::Xesam::rowCount()
{
    return s_xesam()->xesam_rowCount;
}

QUrl Soprano::Vocabulary::Xesam::rssFeed()
{
    return s_xesam()->xesam_rssFeed;
}

QUrl Soprano::Vocabulary::Xesam::sampleConfiguration()
{
    return s_xesam()->xesam_sampleConfiguration;
}

QUrl Soprano::Vocabulary::Xesam::sampleDataBitDepth()
{
    return s_xesam()->xesam_sampleDataBitDepth;
}

QUrl Soprano::Vocabulary::Xesam::sampleDataType()
{
    return s_xesam()->xesam_sampleDataType;
}

QUrl Soprano::Vocabulary::Xesam::secondaryRecipient()
{
    return s_xesam()->xesam_secondaryRecipient;
}

QUrl Soprano::Vocabulary::Xesam::seenAttachedAs()
{
    return s_xesam()->xesam_seenAttachedAs;
}

QUrl Soprano::Vocabulary::Xesam::setCount()
{
    return s_xesam()->xesam_setCount;
}

QUrl Soprano::Vocabulary::Xesam::setRate()
{
    return s_xesam()->xesam_setRate;
}

QUrl Soprano::Vocabulary::Xesam::sha1Hash()
{
    return s_xesam()->xesam_sha1Hash;
}

QUrl Soprano::Vocabulary::Xesam::size()
{
    return s_xesam()->xesam_size;
}

QUrl Soprano::Vocabulary::Xesam::sourceCreated()
{
    return s_xesam()->xesam_sourceCreated;
}

QUrl Soprano::Vocabulary::Xesam::sourceModified()
{
    return s_xesam()->xesam_sourceModified;
}

QUrl Soprano::Vocabulary::Xesam::storageSize()
{
    return s_xesam()->xesam_storageSize;
}

QUrl Soprano::Vocabulary::Xesam::subject()
{
    return s_xesam()->xesam_subject;
}

QUrl Soprano::Vocabulary::Xesam::summary()
{
    return s_xesam()->xesam_summary;
}

QUrl Soprano::Vocabulary::Xesam::supercedes()
{
    return s_xesam()->xesam_supercedes;
}

QUrl Soprano::Vocabulary::Xesam::targetQuality()
{
    return s_xesam()->xesam_targetQuality;
}

QUrl Soprano::Vocabulary::Xesam::title()
{
    return s_xesam()->xesam_title;
}

QUrl Soprano::Vocabulary::Xesam::to()
{
    return s_xesam()->xesam_to;
}

QUrl Soprano::Vocabulary::Xesam::totalSpace()
{
    return s_xesam()->xesam_totalSpace;
}

QUrl Soprano::Vocabulary::Xesam::totalUncompressedSize()
{
    return s_xesam()->xesam_totalUncompressedSize;
}

QUrl Soprano::Vocabulary::Xesam::trackGain()
{
    return s_xesam()->xesam_trackGain;
}

QUrl Soprano::Vocabulary::Xesam::trackNumber()
{
    return s_xesam()->xesam_trackNumber;
}

QUrl Soprano::Vocabulary::Xesam::trackPeakGain()
{
    return s_xesam()->xesam_trackPeakGain;
}

QUrl Soprano::Vocabulary::Xesam::url()
{
    return s_xesam()->xesam_url;
}

QUrl Soprano::Vocabulary::Xesam::useCount()
{
    return s_xesam()->xesam_useCount;
}

QUrl Soprano::Vocabulary::Xesam::userComment()
{
    return s_xesam()->xesam_userComment;
}

QUrl Soprano::Vocabulary::Xesam::userKeyword()
{
    return s_xesam()->xesam_userKeyword;
}

QUrl Soprano::Vocabulary::Xesam::userRating()
{
    return s_xesam()->xesam_userRating;
}

QUrl Soprano::Vocabulary::Xesam::usesNamespace()
{
    return s_xesam()->xesam_usesNamespace;
}

QUrl Soprano::Vocabulary::Xesam::version()
{
    return s_xesam()->xesam_version;
}

QUrl Soprano::Vocabulary::Xesam::verticalResolution()
{
    return s_xesam()->xesam_verticalResolution;
}

QUrl Soprano::Vocabulary::Xesam::videoBitrate()
{
    return s_xesam()->xesam_videoBitrate;
}

QUrl Soprano::Vocabulary::Xesam::videoCodec()
{
    return s_xesam()->xesam_videoCodec;
}

QUrl Soprano::Vocabulary::Xesam::videoCodecType()
{
    return s_xesam()->xesam_videoCodecType;
}

QUrl Soprano::Vocabulary::Xesam::whiteBalance()
{
    return s_xesam()->xesam_whiteBalance;
}

QUrl Soprano::Vocabulary::Xesam::width()
{
    return s_xesam()->xesam_width;
}

QUrl Soprano::Vocabulary::Xesam::wordCount()
{
    return s_xesam()->xesam_wordCount;
}

QUrl Soprano::Vocabulary::Xesam::workEmailAddress()
{
    return s_xesam()->xesam_workEmailAddress;
}

QUrl Soprano::Vocabulary::Xesam::workPhoneNumber()
{
    return s_xesam()->xesam_workPhoneNumber;
}

QUrl Soprano::Vocabulary::Xesam::workPostalAddress()
{
    return s_xesam()->xesam_workPostalAddress;
}
