FIND_PROGRAM(REDLANDCONFIG_EXECUTABLE NAMES redland-config PATHS
   /usr/bin
   /usr/local/bin
)
#reset vars
set(REDLAND_LIBRARIES)
set(REDLAND_CFLAGS)

# if redland-config has been found
IF(REDLANDCONFIG_EXECUTABLE)

  EXEC_PROGRAM(${REDLANDCONFIG_EXECUTABLE} ARGS --libs RETURN_VALUE _return_VALUE OUTPUT_VARIABLE REDLAND_LIBRARIES)

  EXEC_PROGRAM(${REDLANDCONFIG_EXECUTABLE} ARGS --cflags RETURN_VALUE _return_VALUE OUTPUT_VARIABLE REDLAND_CFLAGS)

  IF(REDLAND_LIBRARIES AND REDLAND_CFLAGS)
    SET(Redland_FOUND TRUE)
    message(STATUS "Found redland: ${REDLAND_LIBRARIES}")
  ENDIF(REDLAND_LIBRARIES AND REDLAND_CFLAGS)

  MARK_AS_ADVANCED(REDLAND_CFLAGS REDLAND_LIBRARIES)

ELSE(REDLANDCONFIG_EXECUTABLE)
   SET(Redland_FOUND FALSE)
   message(FATAL_ERROR "redland library not found") 
ENDIF(REDLANDCONFIG_EXECUTABLE)
