FIND_PROGRAM(RAPTORCONFIG_EXECUTABLE NAMES raptor-config PATHS
   /usr/bin
   /usr/local/bin
   /home/duncan/sw/redland/bin
)
#reset vars
set(RAPTOR_LIBRARIES)
set(RAPTOR_CFLAGS)

# if taglib-config has been found
IF(RAPTORCONFIG_EXECUTABLE)

  EXEC_PROGRAM(${RAPTORCONFIG_EXECUTABLE} ARGS --libs RETURN_VALUE _return_VALUE OUTPUT_VARIABLE RAPTOR_LIBRARIES)

  EXEC_PROGRAM(${RAPTORCONFIG_EXECUTABLE} ARGS --cflags RETURN_VALUE _return_VALUE OUTPUT_VARIABLE RAPTOR_CFLAGS)

  IF(RAPTOR_LIBRARIES AND RAPTOR_CFLAGS)
    SET(RAPTOR_FOUND TRUE)
    message(STATUS "Found raptor: ${RAPTOR_LIBRARIES}")
  ENDIF(RAPTOR_LIBRARIES AND RAPTOR_CFLAGS)

  MARK_AS_ADVANCED(RAPTOR_CFLAGS RAPTOR_LIBRARIES)

ENDIF(RAPTORCONFIG_EXECUTABLE)
