FIND_PROGRAM(RASQALCONFIG_EXECUTABLE NAMES rasqal-config PATHS
   /usr/bin
   /usr/local/bin
   /home/duncan/sw/redland/bin
)
#reset vars
set(RASQAL_LIBRARIES)
set(RASQAL_CFLAGS)

# if taglib-config has been found
IF(RASQALCONFIG_EXECUTABLE)

  EXEC_PROGRAM(${RASQALCONFIG_EXECUTABLE} ARGS --libs RETURN_VALUE _return_VALUE OUTPUT_VARIABLE RASQAL_LIBRARIES)

  EXEC_PROGRAM(${RASQALCONFIG_EXECUTABLE} ARGS --cflags RETURN_VALUE _return_VALUE OUTPUT_VARIABLE RASQAL_CFLAGS)

  IF(RASQAL_LIBRARIES AND RASQAL_CFLAGS)
    SET(RASQAL_FOUND TRUE)
    message(STATUS "Found rasqal: ${RASQAL_LIBRARIES}")
  ENDIF(RASQAL_LIBRARIES AND RASQAL_CFLAGS)

  MARK_AS_ADVANCED(RASQAL_CFLAGS RASQAL_LIBRARIES)

ENDIF(RASQALCONFIG_EXECUTABLE)
